---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: cpantestbucket000999
      aws_access_key: ASIASYYEA7DMDS6ZPR75
      aws_secret_key: 787MRppjDBxUKELofL+jwTML/7QzRLY1Hx82LorQ
      security_token: FwoGZXIvYXdzEF8aDHoDXeDgTOVbNf6nrCK6AezkbkNOmh89XBNTsAz/dUbYFtJJkrWJ+n1UilY6YVc2u3W2ToxfjzAIfh/1ifELlooaqrwTPGCLXQMKFVpl+VsJwb8uBz7F4vqfOHEmAga8WbkhfcCj97QvaumuQfmdBjj6drEFSd+Apmxb3ZrHeqT1tPlYRpxhXSt8naNTpUulFL4cUVg1R68iPYCXfS/WZvdePsBINjnLUk4XBa5wDiN846FkD0UKnvmuoGqsr3enWrRGsYVO7Al6cyiolumMBjItIgoMuynQLxofOBc5tJOFAyXBGzeB+P9p1ZCo3ESzm6JaGVJNWfRZ7n/kB/fz
      policy: "{{ lookup('file','../files/bpolicy.json') }}"
      state: present
      region: us-east-1
      versioning: no
      tags:
         name: cpantestbucket000999
         type: example

