---
- name: setting up a LAMP website
  hosts: group1
  become: yes
  tasks:
    - name: install latest version of all required packages
      apt:
        name: 
          - ufw
          - apache2
          - mariadb-server
          - php
          - php-mysql
        state: latest
     
    - name: firewalld enabled and running
      service:
        name: ufw
        enabled: true
        state: started

    - name: firewalld permit http service
      ufw: 
        rule: allow
        port: 80

    - name: http enable and ensure running
      service:
        name: apache2
        enabled: true
        state: started

    - name: mariadb enable and ensure running
      service:
        name: mariadb
        enabled: true
        state: started

    - name: copy the php page from remote using get_url
      get_url:
        url: "https://www.middlewareinventory.com/index.php"
        dest: /var/www/html/index.php
        mode: 0644

    - name: test the webpage/website we have setup
      uri:
        url: http://{{ ansible_hostname }}/index.php
        status_code: 200
