---
- hosts: localhost
  tasks:
    - name: make sure the /tmp has more than 1gb
      shell: "df -h /tmp | grep -v File | awk '{print $4}' | cut -d G -f1"
      register: tmpspace
      failed_when: "tmpspace.stdout|float < 1"

    - name: making sure /opt has more than 4 gb
      shell: "df -h /opt | grep -v File | awk '{print $4}' | cut -d G -f1"
      register: optspace
      failed_when: "optspace.stdout|float < 4"

    - name: make sure RAM is more than 16gb
      shell: "cat /proc/meminfo | grep -i memtotal | awk '{print $2/1024/1024}'"
      register: memory
      failed_when: "memory.stdout|float < 16"
