---
- name: install pip and pip docker
  hosts: all
  tasks:
    - name: install python3-pip3
      apt: 
        name: python3-pip
        state: latest

    - name: install pip3 docker
      pip: 
        name: docker
        executable: pip3


