---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install update (apt)
      when: ansible_distribution == "Debian"
      package:
        name: jq
        state: latest
